inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [nodejs-java]
- alias:  operation
  values: [stamp]
- alias:  fileformat
  values: [ jpeg ]

generationRules:
  include:
  - fileformat[jpeg]
  
outputPath: "signature\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
