inherits: ..\\products.yml

dimensions:  
- alias:  operation
  values: [verify] 
- alias:  signaturetype
  values: [text]
- alias:  fileformat
  values: [pdf, doc, docx, docm, dot, dotm, dotx, odt, ott, rtf, xls, xlsx, xlsm, xlsb, csv, ods, ots, xltx, xltm, ppt, pptx, pps, ppsx, odp, otp, potx, potm, pptm, ppsm, zip, tar, 7z]

dictionaries: ["..\\..\\data\\otherformats.json"]

generationRules:
  include:
  - signaturetype[text] + fileformat[pdf, doc, docx, docm, dot, dotm, dotx, odt, ott, rtf, xls, xlsx, xlsm, xlsb, csv, ods, ots, xltx, xltm, ppt, pptx, pps, ppsx, odp, otp, potx, potm, pptm, ppsm, zip, tar, 7z]
  
outputPath: "signature\\{product}\\{operation}\\{signaturetype}\\{fileformat}.{lang}.md"
