inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [verify]
- alias:  fileformat
  values: [ docx, pdf, pptx, xlsx ]

generationRules:
  include:
  - fileformat[docx, pdf, pptx, xlsx]
  
outputPath: "signature\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
