inherits: products.yml

dimensions:  
- alias:  operation
  values: [sign] 
- alias:  signaturetype
  values: [text]
- alias:  fileformat
  values: [pdf, doc, docx, docm, dot, dotm, dotx, odt, ott, rtf, xls, xlsx, xlsm, xlsb, csv, ods, ots, xltx, xltm, ppt, pptx, pps, ppsx, odp, otp, potx, potm, pptm, ppsm, png, jpeg, bmp, gif, tiff, svg, webp, wmf]

dictionaries: ["..\\data\\otherformats.json"]

generationRules:
  include:
  - signaturetype[text] + fileformat[pdf, doc, docx, docm, dot, dotm, dotx, odt, ott, rtf, xls, xlsx, xlsm, xlsb, csv, ods, ots, xltx, xltm, ppt, pptx, pps, ppsx, odp, otp, potx, potm, pptm, ppsm, png, jpeg, bmp, gif, tiff, svg, webp, wmf]
  
outputPath: "{lang}\\signature\\{product}\\{operation}\\{signaturetype}\\{fileformat}.md"
