inherits: products.yml

dimensions: 
- alias:  signaturetype
  values: [qrcode]
- alias:  qrcodetype
  values: [QR, Aztec]
- alias:  fileformat
  values: [pdf, doc, docx, docm, dot, dotm, dotx, odt, ott, rtf, xls, xlsx, xlsm, xlsb, csv, ods, ots, xltx, xltm, ppt, pptx, pps, ppsx, odp, otp, potx, potm, pptm, ppsm, png, jpg, bmp, gif, tif, tiff, svg, webp, wmf]

dictionaries: ["..\\data\\otherformats.json"]

generationRules:
  include:
  - signaturetype[qrcode] + fileformat[pdf, doc, docx, docm, dot, dotm, dotx, odt, ott, rtf, xls, xlsx, xlsm, xlsb, csv, ods, ots, xltx, xltm, ppt, pptx, pps, ppsx, odp, otp, potx, potm, pptm, ppsm, png, jpg, bmp, gif, tif, tiff, svg, webp, wmf]
  
outputPath: "{lang}\\signature\\{product}\\sign\\{signaturetype}\\{qrcodetype}-{fileformat}.md"
