dimensions: 
- alias: lang
  values: [en, de, es, fr, ja, ko, ru, zh, id, ar, bg, af, am, ca, cs, da, el, et, fa, hi, hu, hy, is, it, ka, kk, ku, lt, lv, ms, nl, pl, pt, ro, sk, sl, sv, th, tr, uk, ur, vi]

dictionaries: ["..\\data\\{operation}\\{lang}.json"]